site_name: Dweeter
site_description: Encrypted messaging through the free dweet service.
site_author: Quan Lin

repo_url: https://github.com/jacklinquan/dweeter
edit_uri: ""

theme:
    name: material

docs_dir: md_docs

site_dir: docs

nav:
    - Home: index.md
    - API Documentation: api.md

copyright: Copyright &copy; 2024 <a href="https://github.com/jacklinquan">Quan Lin</a>.

plugins:
    - search
    - mkapi
